### ISSUE TITLE
Shows all weights instead of only "max of"

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-relevance-ranking-analysis#12]
In some cases (maybe some Synonymgraphfilter structures) all weights are shown, not only "max of" weights.

Maybe because of structure like "
2983.3936 = sum of:
  1770.5753 = max of:
    349.35358 = sum of:
"
since
"
2310.7383 = sum of:
  1373.0211 = sum of:
    747.4061 = max of:
"
seems to work.

**Comment by Mandalka** [comment]
All children of inactive children now inactive, too, for such cases where weights are children of a sum child instead of direct children of a max of.
