### ISSUE TITLE
Fields with synonym graph filter

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr-relevance-ranking-analysis#6]
Support synonym graph syntax in search result, so fields with configured synonym graph filter are displayed correct.

**Comment by Mandalka** [comment]
Implemented enhanced analysis for debug infos by Synonym Graph Filter, so fieldnames in field color map are now displayed (without Synonymfunction name prefix Synonym(...)) and the synonyms in term weight visualization displayed more pretty without (same) fieldname as prefix.
